### ISSUE TITLE
How can i make the drone fly

### ISSUE THREAD

**Issue by aceyhz** [Vision4UAV/cvg_ardrone2_ibvs#15]
Hi
Q1:After the installation of code on the laptop,how can i connect the drone and make it fly?
Q2:Some errors just happened when i start the code, ./parrot_IBVSController_launchers_Release.sh.
./parrot_IBVSController_launchers_Release.sh: Line 46:gnome-terminal: command not found
./parrot_IBVSController_launchers_Release.sh: Line 13:gnome-terminal: command not found
Would you please answer my questions specifically,thank you.

**Comment by jespestana** [comment]
> Q1:After the installation of code on the laptop,how can i connect the drone and make it fly?
You need to step into the problem gradually. First go through the tutorials and information from the ROS node that communicates with the Micro Aerial Vehicle (MAV). We are using this package to communicate with the MAV:
https://github.com/AutonomyLab/ardrone_autonomy

Then, try to create your own ROS node to fly manually using the keyboard, you should be able to command the drone to go up/down/left/right/front/back/rotate_right/rotate_left.

> Q2:Some errors just happened when i start the code, ./parrot_IBVSController_launchers_Release.sh.
> ./parrot_IBVSController_launchers_Release.sh: Line 46:gnome-terminal: command not found
> ./parrot_IBVSController_launchers_Release.sh: Line 13:gnome-terminal: command not found
Please, familiarize yourself with ROS and linux/Ubuntu.

Also, be more descriptive about the problem that you are facing. Many times in the process of describing the problem that you have, you may come up with a solution. Please google about it "Bug reporting guidelines". For instance this website came up:
https://developer.mozilla.org/en-US/docs/Mozilla/QA/Bug_writing_guidelines
