### ISSUE TITLE
question about calibrate the AR Drone 2 camera

### ISSUE THREAD

**Issue by janis2015** [Vision4UAV/cvg_ardrone2_ibvs#3]
When I try to calibrate the camera, I do not know where is the folder '~/.ros/camera_info', anyone can help?

Thank you.

**Comment by suarez-ramon** [comment]
@janis2015 
Hi,

The ~/.ros folder is hidden in the home folder. If you ctrl-h you will find it. If you are using the stack for the first time the ~/.ros/camera_info will not be there so you need to make the directory. After this copy the .yaml files and you should be good to go.

**Comment by janis2015** [comment]
Thank you so much~
