### ISSUE TITLE
Problem with the State Estimator

### ISSUE THREAD

**Issue by elmtam** [Vision4UAV/cvg_ardrone2_ibvs#7]
Hi could anyone help me regarding this problem I am having? The drone is able to pick up the tracked object with the bounding box and is able stable tracking the object. When I execute takeoff, then switch the controller on, that is when the problme arises, the drone is moving erratically as in either too fast towards the tracked object causing the tracked object to move out of the bouding box and I am guessing it is due to the odometry problems. The two screenshots shows the errors I am having while the drone is tracking an object. I am sure it is not a problem with the drone itself as I have managed to calibrate it and have replaced the central cross section of drone as well as calibrating and done a flat trimm of the drone before executing the drone every time. Any help is very much appreciated. Thank you.
![screenshot from 2016-05-01 12 10 43](https://cloud.githubusercontent.com/assets/9165681/14941513/a8f7a608-0f96-11e6-987f-70f5b055bce1.png)
![screenshot from 2016-03-15 08 22 03](https://cloud.githubusercontent.com/assets/9165681/14941516/ad064d3a-0f96-11e6-9356-48061251561e.png)

**Comment by elmtam** [comment]
@suarez-ramon ,

Hi Suarez-ramon I apologise but if you can of help that would be great. Thanks in advance.

**Comment by suarez-ramon** [comment]
Hello,

Have you tried selecting a bigger ROI in the tld gui. Usually when the
drone starts tracking and gets too close to an object, the problem is that
the selected object has a smaller ROI than it can handle or its too far
away.

Cheers

**Comment by jespestana** [comment]
The droneOdometryStateEstimator is not necessary, just take it out from the
launchfile and try again.

**Comment by elmtam** [comment]
Hi @suarez-ramon thank you for your reply. Yes I have tried again and have used a bigger ROI but as soon as I start the controller, the drones starts moving erratically (quickly to the tracked object ) causing the object to move out of frame thus then hovering. Initially when I select the bounding box, click enter and allow some time for the tracker to learn the object, then switch off the learning, takeoff, it is fine. Then when I click start controller, the drone is not tracking the object at a fixed distance. Any suggestion to go about the matter? Thank you again.

**Comment by elmtam** [comment]
Hi @jespestana I am humbled that you replied. Thank you for your time. In other words, do i delete the droneSelfLocalization folder from the stack file?

**Comment by jespestana** [comment]
Hi @elmtam , no problem. How are you launching the software?

If you are using the script "parrot_IBVSController_launcher_Release.sh",
then it is easy to get the droneOdometryStateEstimator out. Just comment
the lines (or delete them) in the script
"parrot_IBVSController_launcher_Release.sh":
  --tab --title "EKF" --command "bash -c \"
roslaunch droneEKFStateEstimatorROSModule
droneEKFStateEstimatorROSModule.launch --wait
drone_id_namespace:=drone$NUMID_DRONE drone_id_int:=$NUMID_DRONE
my_stack_directory:=${IBVS_STACK};
      exec bash\"" \

Let us know if it works then.

**Comment by elmtam** [comment]
Hi @jespestana after commenting out the EKF lines, the drone is more stable and not moving erratically but once im tracking an object and toggled learning (to switch off the learning and execute only tracking), the drone is not moving in line with the tracked object. As in once the controller is switched on, the drone is not moving towards, or the body of the drone is not turning towards the tracked object. Any help is appreciated. Thank you again.

**Comment by jespestana** [comment]
Hi @elmtam . Ok good, the EKF is not needed.

As to the rest of your problems, you probably need to study the console
interface keys and experiment with them. They are explained here
https://github.com/Vision4UAV/cvg_ardrone2_ibvs#interaction-with-ui . You
need to know how to toggle the contrller on and off m etc.

**Comment by elmtam** [comment]
@jespestana Hi i have made multiple tests after commenting out the EKF out of the launcher, the drone is very stable in taking off and hovering. However this causes the controller to be switched on as soon as the tracker is "ON" as well. Despite the controller being "ON", the drone is not responding to the tracked object. It can be seen on the gui and real time srtream that the object is being tracked successfully and is "IN FRAME" but the drone is not making any movements relative to the movement of the tracked object. Please provide me with any guidance thank you.

**Comment by elmtam** [comment]
@jespestana is it possible that this problem arises due to the OpenTLD/ ar drone autonomy? Thank you for your time

**Comment by elmtam** [comment]
@suarez-ramon Hi suarez ramon could you provide any guidance? Thank you in advance

**Comment by AloshkaD** [comment]
Hi elmtam,

How did you fix the issue with StateEstimator? I read in 8 that you have  eventually found a fix to that bug. Thanks!
